_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 71
                - 95
                - 105
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 71
                - 95
                - 105
            "3":
                - 2
                - 13
                - 16
                - 55
                - 61
            "4": 3.10.18
            "5": 0.20.1
            "6": 4.51.3
            "12": 0.20.1
            "13": linux-x86_64
actor_rollout_ref:
    value:
        actor:
            clip_ratio: 0.2
            entropy_coeff: 0.001
            fsdp_config:
                fsdp_size: -1
                grad_offload: false
                optimizer_offload: false
                param_offload: false
                wrap_policy:
                    min_num_params: 0
            grad_clip: 1
            kl_loss_coef: 0.001
            kl_loss_type: low_var_kl
            optim:
                lr: 1e-06
                lr_warmup_steps_ratio: 0
                min_lr_ratio: null
                total_training_steps: 8000
                warmup_style: constant
            ppo_epochs: 1
            ppo_max_token_len_per_gpu: 24000
            ppo_micro_batch_size: null
            ppo_micro_batch_size_per_gpu: null
            ppo_mini_batch_size: 30
            shuffle: false
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_dynamic_bsz: true
            use_kl_loss: true
        hybrid_engine: true
        model:
            enable_gradient_checkpointing: true
            external_lib: null
            path: /homes/gws/lxh22/models/Qwen2.5-Math-1.5B
            use_remove_padding: true
            use_think: false
        ref:
            fsdp_config:
                param_offload: true
                wrap_policy:
                    min_num_params: 0
            log_prob_max_token_len_per_gpu: 24000
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: null
            log_prob_use_dynamic_bsz: true
            ulysses_sequence_parallel_size: 1
        rollout:
            disable_log_stats: true
            do_sample: true
            dtype: bfloat16
            enable_chunked_prefill: true
            enforce_eager: true
            free_cache_engine: true
            gpu_memory_utilization: 0.7
            ignore_eos: false
            load_format: dummy_dtensor
            log_prob_max_token_len_per_gpu: 24000
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: null
            log_prob_use_dynamic_bsz: true
            max_num_batched_tokens: 8192
            max_num_seqs: 1024
            "n": 8
            n_val: 1
            name: vllm
            prompt_length: 1024
            response_length: 3072
            temperature: 0.6
            tensor_model_parallel_size: 2
            top_k: -1
            top_p: 1
            val_temperature: 0.6
algorithm:
    value:
        adv_estimator: grpo
        gamma: 1
        kl_ctrl:
            kl_coef: 0.001
            type: fixed
        kl_penalty: kl
        lam: 1
critic:
    value:
        cliprange_value: 0.5
        forward_max_token_len_per_gpu: 32768
        forward_micro_batch_size: null
        forward_micro_batch_size_per_gpu: null
        grad_clip: 1
        model:
            enable_gradient_checkpointing: true
            external_lib: null
            fsdp_config:
                fsdp_size: -1
                optimizer_offload: false
                param_offload: false
                wrap_policy:
                    min_num_params: 0
            path: ~/models/deepseek-llm-7b-chat
            tokenizer_path: /homes/gws/lxh22/models/Qwen2.5-Math-1.5B
            use_remove_padding: false
        optim:
            lr: 1e-05
            lr_warmup_steps_ratio: 0
            min_lr_ratio: null
            total_training_steps: 8000
            warmup_style: constant
        ppo_epochs: 1
        ppo_max_token_len_per_gpu: 32768
        ppo_micro_batch_size: null
        ppo_micro_batch_size_per_gpu: null
        ppo_mini_batch_size: 30
        shuffle: false
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: true
data:
    value:
        max_prompt_length: 1024
        max_response_length: 3072
        prompt_key: prompt
        return_raw_chat: false
        return_raw_input_ids: false
        shuffle: true
        tokenizer: null
        train_batch_size: 30
        train_files: data/train/one_shot_rlvr/dsr_sub.parquet
        val_batch_size: 53
        val_files: data/test/math500.parquet
reward_model:
    value:
        enable: false
        forward_max_token_len_per_gpu: 32768
        max_length: null
        micro_batch_size: null
        micro_batch_size_per_gpu: null
        model:
            external_lib: null
            fsdp_config:
                fsdp_size: -1
                min_num_params: 0
                param_offload: false
            input_tokenizer: /homes/gws/lxh22/models/Qwen2.5-Math-1.5B
            path: ~/models/FsfairX-LLaMA3-RM-v0.1
            use_remove_padding: false
        reward_manager: naive
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: true
trainer:
    value:
        checkpoints_dir: /local1/lxh/save
        critic_warmup: 0
        default_hdfs_dir: null
        default_local_dir: /local1/lxh/save/verl_few_shot/Qwen2.5-Math-1.5B-dsr_sub_offline
        del_local_ckpt_after_load: false
        experiment_name: Qwen2.5-Math-1.5B-dsr_sub_offline
        logger:
            - console
            - wandb
        n_gpus_per_node: 6
        nnodes: 1
        project_name: verl_few_shot
        remove_previous_ckpt_in_save: false
        resume_from_path: false
        resume_mode: auto
        save_freq: 1
        test_freq: 1
        total_epochs: 200
        total_training_steps: null
        val_before_train: true
        val_generations_to_log_to_wandb: 0
